import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



// Load Satoshi from CDN (FontShare)
const satoshi = {
  variable: '--font-satoshi',
  style: 'normal',
  weight: ['400', '500', '700', '900'],
  className: 'font-sans',
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GEORGE RALAK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@400,500,700,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${satoshi.variable} ${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
       
        {children}
       
      </body>
    </html>
  );
}